/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trivy_check

import (
	"encoding/json"
	"fmt"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// Kind - struct for Kind
type Kind struct {
	String *string
}

// StringAsKind is is a convenience function that returns string wrapped in Kind
func StringAsKind(v *string) Kind {
	return Kind{
		String: v,
	}
}

// Validate validates this Kind
func (o *Kind) Validate() error {
	if o.String != nil {
		return nil
	}

	return fmt.Errorf("No oneOf schemas were matched in Kind")
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Kind) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = utils.NewStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Kind)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Kind)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Kind) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Kind) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableKind struct {
	value *Kind
	isSet bool
}

func (v *NullableKind) Get() *Kind {
	return v.value
}

func (v *NullableKind) Set(val *Kind) {
	v.value = val
	v.isSet = true
}

func (v *NullableKind) IsSet() bool {
	return v.isSet
}

func (v *NullableKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKind(val *Kind) *NullableKind {
	return &NullableKind{value: val, isSet: true}
}

func (v NullableKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
