/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package startup_probe

import (
	"encoding/json"
	"errors"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/common"
	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// checks if the StartupProbeSpecOneOf type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &StartupProbeSpecOneOf{}

// StartupProbeSpecOneOf struct for StartupProbeSpecOneOf
type StartupProbeSpecOneOf struct {
	// Specify the startup probe for multiple containers
	Probes []StartupProbeParams `json:"probes"`
}

// NewStartupProbeSpecOneOfWith instantiates a new StartupProbeSpecOneOf object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewStartupProbeSpecOneOfWith(probes []StartupProbeParams) *StartupProbeSpecOneOf {
	this := StartupProbeSpecOneOf{}
	this.Probes = probes
	return &this
}

// NewStartupProbeSpecOneOfWithDefault instantiates a new StartupProbeSpecOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartupProbeSpecOneOfWithDefault() *StartupProbeSpecOneOf {
	this := StartupProbeSpecOneOf{}
	return &this
}

// NewStartupProbeSpecOneOf is short for NewStartupProbeSpecOneOfWithDefault which instantiates a new StartupProbeSpecOneOf object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartupProbeSpecOneOf() *StartupProbeSpecOneOf {
	return NewStartupProbeSpecOneOfWithDefault()
}

// NewStartupProbeSpecOneOfEmpty instantiates a new StartupProbeSpecOneOf object with no properties set.
// This constructor will not assign any default values to properties.
func NewStartupProbeSpecOneOfEmpty() *StartupProbeSpecOneOf {
	this := StartupProbeSpecOneOf{}
	return &this
}

// NewStartupProbeSpecOneOfs converts a list StartupProbeSpecOneOf pointers to objects.
// This is helpful when the SetStartupProbeSpecOneOf requires a list of objects
func NewStartupProbeSpecOneOfList(ps ...*StartupProbeSpecOneOf) []StartupProbeSpecOneOf {
	objs := []StartupProbeSpecOneOf{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this StartupProbeSpecOneOf
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *StartupProbeSpecOneOf) Validate() error {
	if o.Probes == nil {
		return errors.New("Probes in StartupProbeSpecOneOf must be set")
	}
	// validate all nested properties
	return nil
}

// GetProbes returns the Probes field value
func (o *StartupProbeSpecOneOf) GetProbes() []StartupProbeParams {
	if o == nil {
		var ret []StartupProbeParams
		return ret
	}

	return o.Probes
}

// GetProbesOk returns a tuple with the Probes field value
// and a boolean to check if the value has been set.
func (o *StartupProbeSpecOneOf) GetProbesOk() ([]StartupProbeParams, bool) {
	if o == nil {
		return nil, false
	}
	return o.Probes, true
}

// SetProbes sets field value
func (o *StartupProbeSpecOneOf) SetProbes(v []StartupProbeParams) *StartupProbeSpecOneOf {
	o.Probes = v
	return o
}

func (o StartupProbeSpecOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartupProbeSpecOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["probes"] = o.Probes
	return toSerialize, nil
}

type NullableStartupProbeSpecOneOf struct {
	value *StartupProbeSpecOneOf
	isSet bool
}

func (v *NullableStartupProbeSpecOneOf) Get() *StartupProbeSpecOneOf {
	return v.value
}

func (v *NullableStartupProbeSpecOneOf) Set(val *StartupProbeSpecOneOf) {
	v.value = val
	v.isSet = true
}

func (v *NullableStartupProbeSpecOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStartupProbeSpecOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartupProbeSpecOneOf(val *StartupProbeSpecOneOf) *NullableStartupProbeSpecOneOf {
	return &NullableStartupProbeSpecOneOf{value: val, isSet: true}
}

func (v NullableStartupProbeSpecOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartupProbeSpecOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
