/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nocalhost

import (
	"encoding/json"
	"errors"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/common"
	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// checks if the PersistentVolumeDirs type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &PersistentVolumeDirs{}

// PersistentVolumeDirs struct for PersistentVolumeDirs
type PersistentVolumeDirs struct {
	Capacity *string `json:"capacity"`
	Path     *string `json:"path"`
}

// NewPersistentVolumeDirsWith instantiates a new PersistentVolumeDirs object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewPersistentVolumeDirsWith(capacity string, path string) *PersistentVolumeDirs {
	this := PersistentVolumeDirs{}
	this.Capacity = &capacity
	this.Path = &path
	return &this
}

// NewPersistentVolumeDirsWithDefault instantiates a new PersistentVolumeDirs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersistentVolumeDirsWithDefault() *PersistentVolumeDirs {
	this := PersistentVolumeDirs{}
	return &this
}

// NewPersistentVolumeDirs is short for NewPersistentVolumeDirsWithDefault which instantiates a new PersistentVolumeDirs object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersistentVolumeDirs() *PersistentVolumeDirs {
	return NewPersistentVolumeDirsWithDefault()
}

// NewPersistentVolumeDirsEmpty instantiates a new PersistentVolumeDirs object with no properties set.
// This constructor will not assign any default values to properties.
func NewPersistentVolumeDirsEmpty() *PersistentVolumeDirs {
	this := PersistentVolumeDirs{}
	return &this
}

// NewPersistentVolumeDirss converts a list PersistentVolumeDirs pointers to objects.
// This is helpful when the SetPersistentVolumeDirs requires a list of objects
func NewPersistentVolumeDirsList(ps ...*PersistentVolumeDirs) []PersistentVolumeDirs {
	objs := []PersistentVolumeDirs{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this PersistentVolumeDirs
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *PersistentVolumeDirs) Validate() error {
	if o.Capacity == nil {
		return errors.New("Capacity in PersistentVolumeDirs must be set")
	}
	if o.Path == nil {
		return errors.New("Path in PersistentVolumeDirs must be set")
	}
	// validate all nested properties
	return nil
}

// GetCapacity returns the Capacity field value
func (o *PersistentVolumeDirs) GetCapacity() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value
// and a boolean to check if the value has been set.
func (o *PersistentVolumeDirs) GetCapacityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capacity, true
}

// SetCapacity sets field value
func (o *PersistentVolumeDirs) SetCapacity(v string) *PersistentVolumeDirs {
	o.Capacity = &v
	return o
}

// GetPath returns the Path field value
func (o *PersistentVolumeDirs) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *PersistentVolumeDirs) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path, true
}

// SetPath sets field value
func (o *PersistentVolumeDirs) SetPath(v string) *PersistentVolumeDirs {
	o.Path = &v
	return o
}

func (o PersistentVolumeDirs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersistentVolumeDirs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capacity"] = o.Capacity
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

type NullablePersistentVolumeDirs struct {
	value *PersistentVolumeDirs
	isSet bool
}

func (v *NullablePersistentVolumeDirs) Get() *PersistentVolumeDirs {
	return v.value
}

func (v *NullablePersistentVolumeDirs) Set(val *PersistentVolumeDirs) {
	v.value = val
	v.isSet = true
}

func (v *NullablePersistentVolumeDirs) IsSet() bool {
	return v.isSet
}

func (v *NullablePersistentVolumeDirs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersistentVolumeDirs(val *PersistentVolumeDirs) *NullablePersistentVolumeDirs {
	return &NullablePersistentVolumeDirs{value: val, isSet: true}
}

func (v NullablePersistentVolumeDirs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersistentVolumeDirs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
