/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kustomize

import (
	"encoding/json"
	"errors"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// checks if the Numerical type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Numerical{}

// Numerical Numerical set of rules to use for numerical ordering of the tags.
type Numerical struct {
	// Order specifies the sorting order of the tags. +usage=Given the integer values from 0 to 9 as tags, ascending order would select 9, and descending order would select 0.
	Order *string `json:"order"`
}

// NewNumericalWith instantiates a new Numerical object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewNumericalWith(order string) *Numerical {
	this := Numerical{}
	this.Order = &order
	return &this
}

// NewNumericalWithDefault instantiates a new Numerical object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumericalWithDefault() *Numerical {
	this := Numerical{}
	return &this
}

// NewNumerical is short for NewNumericalWithDefault which instantiates a new Numerical object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumerical() *Numerical {
	return NewNumericalWithDefault()
}

// NewNumericalEmpty instantiates a new Numerical object with no properties set.
// This constructor will not assign any default values to properties.
func NewNumericalEmpty() *Numerical {
	this := Numerical{}
	return &this
}

// NewNumericals converts a list Numerical pointers to objects.
// This is helpful when the SetNumerical requires a list of objects
func NewNumericalList(ps ...*Numerical) []Numerical {
	objs := []Numerical{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Numerical
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Numerical) Validate() error {
	if o.Order == nil {
		return errors.New("Order in Numerical must be set")
	}
	// validate all nested properties
	return nil
}

// GetOrder returns the Order field value
func (o *Numerical) GetOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *Numerical) GetOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order, true
}

// SetOrder sets field value
func (o *Numerical) SetOrder(v string) *Numerical {
	o.Order = &v
	return o
}

func (o Numerical) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Numerical) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

type NullableNumerical struct {
	value *Numerical
	isSet bool
}

func (v *NullableNumerical) Get() *Numerical {
	return v.value
}

func (v *NullableNumerical) Set(val *Numerical) {
	v.value = val
	v.isSet = true
}

func (v *NullableNumerical) IsSet() bool {
	return v.isSet
}

func (v *NullableNumerical) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumerical(val *Numerical) *NullableNumerical {
	return &NullableNumerical{value: val, isSet: true}
}

func (v NullableNumerical) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumerical) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
