/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restart_workflow

import (
	"encoding/json"

	"github.com/kubevela/pkg/apis/oam/v1alpha1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/common"
	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// checks if the RestartWorkflowSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &RestartWorkflowSpec{}

// RestartWorkflowSpec struct for RestartWorkflowSpec
type RestartWorkflowSpec struct {
	// Schedule restart after a relative duration from now (e.g., \"5m\", \"1h\", \"2d\")
	After *string `json:"after,omitempty"`
	// Schedule restart at a specific RFC3339 timestamp (e.g., \"2025-01-15T14:30:00Z\")
	At *string `json:"at,omitempty"`
	// Schedule recurring restarts every specified duration (e.g., \"5m\", \"1h\", \"24h\")
	Every *string `json:"every,omitempty"`
}

// NewRestartWorkflowSpecWith instantiates a new RestartWorkflowSpec object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewRestartWorkflowSpecWith() *RestartWorkflowSpec {
	this := RestartWorkflowSpec{}
	return &this
}

// NewRestartWorkflowSpecWithDefault instantiates a new RestartWorkflowSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartWorkflowSpecWithDefault() *RestartWorkflowSpec {
	this := RestartWorkflowSpec{}
	return &this
}

// NewRestartWorkflowSpec is short for NewRestartWorkflowSpecWithDefault which instantiates a new RestartWorkflowSpec object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartWorkflowSpec() *RestartWorkflowSpec {
	return NewRestartWorkflowSpecWithDefault()
}

// NewRestartWorkflowSpecEmpty instantiates a new RestartWorkflowSpec object with no properties set.
// This constructor will not assign any default values to properties.
func NewRestartWorkflowSpecEmpty() *RestartWorkflowSpec {
	this := RestartWorkflowSpec{}
	return &this
}

// NewRestartWorkflowSpecs converts a list RestartWorkflowSpec pointers to objects.
// This is helpful when the SetRestartWorkflowSpec requires a list of objects
func NewRestartWorkflowSpecList(ps ...*RestartWorkflowSpec) []RestartWorkflowSpec {
	objs := []RestartWorkflowSpec{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this RestartWorkflowSpec
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *RestartWorkflowWorkflowStep) Validate() error {
	// validate all nested properties
	return nil
}

// GetAfter returns the After field value if set, zero value otherwise.
func (o *RestartWorkflowWorkflowStep) GetAfter() string {
	if o == nil || utils.IsNil(o.Properties.After) {
		var ret string
		return ret
	}
	return *o.Properties.After
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartWorkflowWorkflowStep) GetAfterOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Properties.After) {
		return nil, false
	}
	return o.Properties.After, true
}

// HasAfter returns a boolean if a field has been set.
func (o *RestartWorkflowWorkflowStep) HasAfter() bool {
	if o != nil && !utils.IsNil(o.Properties.After) {
		return true
	}

	return false
}

// SetAfter gets a reference to the given string and assigns it to the after field.
// After:  Schedule restart after a relative duration from now (e.g., \"5m\", \"1h\", \"2d\")
func (o *RestartWorkflowWorkflowStep) SetAfter(v string) *RestartWorkflowWorkflowStep {
	o.Properties.After = &v
	return o
}

// GetAt returns the At field value if set, zero value otherwise.
func (o *RestartWorkflowWorkflowStep) GetAt() string {
	if o == nil || utils.IsNil(o.Properties.At) {
		var ret string
		return ret
	}
	return *o.Properties.At
}

// GetAtOk returns a tuple with the At field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartWorkflowWorkflowStep) GetAtOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Properties.At) {
		return nil, false
	}
	return o.Properties.At, true
}

// HasAt returns a boolean if a field has been set.
func (o *RestartWorkflowWorkflowStep) HasAt() bool {
	if o != nil && !utils.IsNil(o.Properties.At) {
		return true
	}

	return false
}

// SetAt gets a reference to the given string and assigns it to the at field.
// At:  Schedule restart at a specific RFC3339 timestamp (e.g., \"2025-01-15T14:30:00Z\")
func (o *RestartWorkflowWorkflowStep) SetAt(v string) *RestartWorkflowWorkflowStep {
	o.Properties.At = &v
	return o
}

// GetEvery returns the Every field value if set, zero value otherwise.
func (o *RestartWorkflowWorkflowStep) GetEvery() string {
	if o == nil || utils.IsNil(o.Properties.Every) {
		var ret string
		return ret
	}
	return *o.Properties.Every
}

// GetEveryOk returns a tuple with the Every field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartWorkflowWorkflowStep) GetEveryOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Properties.Every) {
		return nil, false
	}
	return o.Properties.Every, true
}

// HasEvery returns a boolean if a field has been set.
func (o *RestartWorkflowWorkflowStep) HasEvery() bool {
	if o != nil && !utils.IsNil(o.Properties.Every) {
		return true
	}

	return false
}

// SetEvery gets a reference to the given string and assigns it to the every field.
// Every:  Schedule recurring restarts every specified duration (e.g., \"5m\", \"1h\", \"24h\")
func (o *RestartWorkflowWorkflowStep) SetEvery(v string) *RestartWorkflowWorkflowStep {
	o.Properties.Every = &v
	return o
}

func (o RestartWorkflowSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartWorkflowSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.After) {
		toSerialize["after"] = o.After
	}
	if !utils.IsNil(o.At) {
		toSerialize["at"] = o.At
	}
	if !utils.IsNil(o.Every) {
		toSerialize["every"] = o.Every
	}
	return toSerialize, nil
}

type NullableRestartWorkflowSpec struct {
	value *RestartWorkflowSpec
	isSet bool
}

func (v *NullableRestartWorkflowSpec) Get() *RestartWorkflowSpec {
	return v.value
}

func (v *NullableRestartWorkflowSpec) Set(val *RestartWorkflowSpec) {
	v.value = val
	v.isSet = true
}

func (v *NullableRestartWorkflowSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartWorkflowSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartWorkflowSpec(val *RestartWorkflowSpec) *NullableRestartWorkflowSpec {
	return &NullableRestartWorkflowSpec{value: val, isSet: true}
}

func (v NullableRestartWorkflowSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartWorkflowSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const RestartWorkflowType = "restart-workflow"

func init() {
	sdkcommon.RegisterWorkflowStep(RestartWorkflowType, FromWorkflowStep)
	sdkcommon.RegisterWorkflowSubStep(RestartWorkflowType, FromWorkflowSubStep)
}

type RestartWorkflowWorkflowStep struct {
	Base       apis.WorkflowStepBase
	Properties RestartWorkflowSpec
}

func RestartWorkflow(name string) *RestartWorkflowWorkflowStep {
	r := &RestartWorkflowWorkflowStep{Base: apis.WorkflowStepBase{
		Name: name,
		Type: RestartWorkflowType,
	}}
	return r
}

func (r *RestartWorkflowWorkflowStep) Build() v1alpha1.WorkflowStep {
	_subSteps := make([]v1alpha1.WorkflowStep, 0)
	for _, subStep := range r.Base.SubSteps {
		_subSteps = append(_subSteps, subStep.Build())
	}
	subSteps := make([]v1alpha1.WorkflowStepBase, 0)
	for _, _s := range _subSteps {
		subSteps = append(subSteps, _s.WorkflowStepBase)
	}
	res := v1alpha1.WorkflowStep{
		SubSteps: subSteps,
		WorkflowStepBase: v1alpha1.WorkflowStepBase{
			DependsOn:  r.Base.DependsOn,
			If:         r.Base.If,
			Inputs:     r.Base.Inputs,
			Meta:       r.Base.Meta,
			Name:       r.Base.Name,
			Outputs:    r.Base.Outputs,
			Properties: util.Object2RawExtension(r.Properties),
			Timeout:    r.Base.Timeout,
			Type:       RestartWorkflowType,
		},
	}
	return res
}

func (r *RestartWorkflowWorkflowStep) FromWorkflowStep(from v1alpha1.WorkflowStep) (*RestartWorkflowWorkflowStep, error) {
	var properties RestartWorkflowSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	subSteps := make([]apis.WorkflowStep, 0)
	for _, _s := range from.SubSteps {
		subStep, err := r.FromWorkflowSubStep(_s)
		if err != nil {
			return nil, err
		}
		subSteps = append(subSteps, subStep)
	}
	r.Base.Name = from.Name
	r.Base.DependsOn = from.DependsOn
	r.Base.Inputs = from.Inputs
	r.Base.Outputs = from.Outputs
	r.Base.If = from.If
	r.Base.Timeout = from.Timeout
	r.Base.Meta = from.Meta
	r.Base.Type = RestartWorkflowType
	r.Properties = properties
	r.Base.SubSteps = subSteps
	return r, nil
}

func FromWorkflowStep(from v1alpha1.WorkflowStep) (apis.WorkflowStep, error) {
	r := &RestartWorkflowWorkflowStep{}
	return r.FromWorkflowStep(from)
}

func (r *RestartWorkflowWorkflowStep) FromWorkflowSubStep(from v1alpha1.WorkflowStepBase) (*RestartWorkflowWorkflowStep, error) {
	var properties RestartWorkflowSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	r.Base.Name = from.Name
	r.Base.DependsOn = from.DependsOn
	r.Base.Inputs = from.Inputs
	r.Base.Outputs = from.Outputs
	r.Base.If = from.If
	r.Base.Timeout = from.Timeout
	r.Base.Meta = from.Meta
	r.Base.Type = RestartWorkflowType
	r.Properties = properties
	return r, nil
}

func FromWorkflowSubStep(from v1alpha1.WorkflowStepBase) (apis.WorkflowStep, error) {
	r := &RestartWorkflowWorkflowStep{}
	return r.FromWorkflowSubStep(from)
}

func (r *RestartWorkflowWorkflowStep) WorkflowStepName() string {
	return r.Base.Name
}

func (r *RestartWorkflowWorkflowStep) DefType() string {
	return RestartWorkflowType
}

func (r *RestartWorkflowWorkflowStep) If(_if string) *RestartWorkflowWorkflowStep {
	r.Base.If = _if
	return r
}

func (r *RestartWorkflowWorkflowStep) Alias(alias string) *RestartWorkflowWorkflowStep {
	r.Base.Meta.Alias = alias
	return r
}

func (r *RestartWorkflowWorkflowStep) Timeout(timeout string) *RestartWorkflowWorkflowStep {
	r.Base.Timeout = timeout
	return r
}

func (r *RestartWorkflowWorkflowStep) DependsOn(dependsOn []string) *RestartWorkflowWorkflowStep {
	r.Base.DependsOn = dependsOn
	return r
}

func (r *RestartWorkflowWorkflowStep) Inputs(input v1alpha1.StepInputs) *RestartWorkflowWorkflowStep {
	r.Base.Inputs = input
	return r
}

func (r *RestartWorkflowWorkflowStep) Outputs(output v1alpha1.StepOutputs) *RestartWorkflowWorkflowStep {
	r.Base.Outputs = output
	return r
}
