/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package health

import (
	"encoding/json"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela-contrib/vela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela-contrib/vela-go-sdk/pkg/apis/common"
	"github.com/kubevela-contrib/vela-go-sdk/pkg/apis/utils"
)

// checks if the HealthSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &HealthSpec{}

// HealthSpec struct for HealthSpec
type HealthSpec struct {
	// Specify health checking interval(seconds), default 30s
	ProbeInterval *int32 `json:"probeInterval,omitempty"`
	// Specify health checking timeout(seconds), default 10s
	ProbeTimeout *int32 `json:"probeTimeout,omitempty"`
}

// NewHealthSpecWith instantiates a new HealthSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthSpecWith() *HealthSpec {
	this := HealthSpec{}
	var probeInterval int32 = 30
	this.ProbeInterval = &probeInterval
	var probeTimeout int32 = 10
	this.ProbeTimeout = &probeTimeout
	return &this
}

// NewHealthSpec instantiates a new HealthSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthSpec() *HealthSpec {
	this := HealthSpec{}
	var probeInterval int32 = 30
	this.ProbeInterval = &probeInterval
	var probeTimeout int32 = 10
	this.ProbeTimeout = &probeTimeout
	return &this
}

// NewHealthSpecs converts a list HealthSpec pointers to objects.
// This is helpful when the SetHealthSpec requires a list of objects
func NewHealthSpecList(ps ...*HealthSpec) []HealthSpec {
	objs := []HealthSpec{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// GetProbeInterval returns the ProbeInterval field value if set, zero value otherwise.
func (o *HealthPolicy) GetProbeInterval() int32 {
	if o == nil || utils.IsNil(o.Properties.ProbeInterval) {
		var ret int32
		return ret
	}
	return *o.Properties.ProbeInterval
}

// GetProbeIntervalOk returns a tuple with the ProbeInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthPolicy) GetProbeIntervalOk() (*int32, bool) {
	if o == nil || utils.IsNil(o.Properties.ProbeInterval) {
		return nil, false
	}
	return o.Properties.ProbeInterval, true
}

// HasProbeInterval returns a boolean if a field has been set.
func (o *HealthPolicy) HasProbeInterval() bool {
	if o != nil && !utils.IsNil(o.Properties.ProbeInterval) {
		return true
	}

	return false
}

// SetProbeInterval gets a reference to the given int32 and assigns it to the probeInterval field.
// ProbeInterval:  Specify health checking interval(seconds), default 30s
func (o *HealthPolicy) SetProbeInterval(v int32) *HealthPolicy {
	o.Properties.ProbeInterval = &v
	return o
}

// GetProbeTimeout returns the ProbeTimeout field value if set, zero value otherwise.
func (o *HealthPolicy) GetProbeTimeout() int32 {
	if o == nil || utils.IsNil(o.Properties.ProbeTimeout) {
		var ret int32
		return ret
	}
	return *o.Properties.ProbeTimeout
}

// GetProbeTimeoutOk returns a tuple with the ProbeTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthPolicy) GetProbeTimeoutOk() (*int32, bool) {
	if o == nil || utils.IsNil(o.Properties.ProbeTimeout) {
		return nil, false
	}
	return o.Properties.ProbeTimeout, true
}

// HasProbeTimeout returns a boolean if a field has been set.
func (o *HealthPolicy) HasProbeTimeout() bool {
	if o != nil && !utils.IsNil(o.Properties.ProbeTimeout) {
		return true
	}

	return false
}

// SetProbeTimeout gets a reference to the given int32 and assigns it to the probeTimeout field.
// ProbeTimeout:  Specify health checking timeout(seconds), default 10s
func (o *HealthPolicy) SetProbeTimeout(v int32) *HealthPolicy {
	o.Properties.ProbeTimeout = &v
	return o
}

func (o HealthSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.ProbeInterval) {
		toSerialize["probeInterval"] = o.ProbeInterval
	}
	if !utils.IsNil(o.ProbeTimeout) {
		toSerialize["probeTimeout"] = o.ProbeTimeout
	}
	return toSerialize, nil
}

type NullableHealthSpec struct {
	value *HealthSpec
	isSet bool
}

func (v NullableHealthSpec) Get() *HealthSpec {
	return v.value
}

func (v *NullableHealthSpec) Set(val *HealthSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthSpec(val *HealthSpec) *NullableHealthSpec {
	return &NullableHealthSpec{value: val, isSet: true}
}

func (v NullableHealthSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const HealthType = "health"

func init() {
	sdkcommon.RegisterPolicy(HealthType, FromPolicy)
}

type HealthPolicy struct {
	Base       apis.PolicyBase
	Properties HealthSpec
}

func Health(name string) *HealthPolicy {
	h := &HealthPolicy{Base: apis.PolicyBase{
		Name: name,
		Type: HealthType,
	}}
	return h
}

func (h *HealthPolicy) Build() v1beta1.AppPolicy {
	res := v1beta1.AppPolicy{
		Name:       h.Base.Name,
		Properties: util.Object2RawExtension(h.Properties),
		Type:       HealthType,
	}
	return res
}

func (h *HealthPolicy) FromPolicy(from v1beta1.AppPolicy) (*HealthPolicy, error) {
	var properties HealthSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	h.Base.Name = from.Name
	h.Base.Type = HealthType
	h.Properties = properties
	return h, nil
}

func FromPolicy(from v1beta1.AppPolicy) (apis.Policy, error) {
	h := &HealthPolicy{}
	return h.FromPolicy(from)
}

func (h *HealthPolicy) PolicyName() string {
	return h.Base.Name
}

func (h *HealthPolicy) DefType() string {
	return HealthType
}
