/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apply_terraform_provider

import (
	"encoding/json"
	"errors"

	"github.com/kubevela-contrib/kubevela-go-sdk/pkg/apis/utils"
)

// checks if the GCPProvider type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &GCPProvider{}

// GCPProvider struct for GCPProvider
type GCPProvider struct {
	Credentials *string `json:"credentials"`
	Name        *string `json:"name"`
	Project     *string `json:"project"`
	Region      *string `json:"region"`
	Type        *string `json:"type"`
}

// NewGCPProviderWith instantiates a new GCPProvider object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewGCPProviderWith(credentials string, name string, project string, region string, type_ string) *GCPProvider {
	this := GCPProvider{}
	this.Credentials = &credentials
	this.Name = &name
	this.Project = &project
	this.Region = &region
	this.Type = &type_
	return &this
}

// NewGCPProviderWithDefault instantiates a new GCPProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCPProviderWithDefault() *GCPProvider {
	this := GCPProvider{}
	var name string = "gcp-provider"
	this.Name = &name
	return &this
}

// NewGCPProvider is short for NewGCPProviderWithDefault which instantiates a new GCPProvider object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCPProvider() *GCPProvider {
	return NewGCPProviderWithDefault()
}

// NewGCPProviderEmpty instantiates a new GCPProvider object with no properties set.
// This constructor will not assign any default values to properties.
func NewGCPProviderEmpty() *GCPProvider {
	this := GCPProvider{}
	return &this
}

// NewGCPProviders converts a list GCPProvider pointers to objects.
// This is helpful when the SetGCPProvider requires a list of objects
func NewGCPProviderList(ps ...*GCPProvider) []GCPProvider {
	objs := []GCPProvider{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this GCPProvider
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *GCPProvider) Validate() error {
	if o.Credentials == nil {
		return errors.New("Credentials in GCPProvider must be set")
	}
	if o.Name == nil {
		return errors.New("Name in GCPProvider must be set")
	}
	if o.Project == nil {
		return errors.New("Project in GCPProvider must be set")
	}
	if o.Region == nil {
		return errors.New("Region in GCPProvider must be set")
	}
	if o.Type == nil {
		return errors.New("Type in GCPProvider must be set")
	}
	// validate all nested properties
	return nil
}

// GetCredentials returns the Credentials field value
func (o *GCPProvider) GetCredentials() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *GCPProvider) GetCredentialsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials, true
}

// SetCredentials sets field value
func (o *GCPProvider) SetCredentials(v string) *GCPProvider {
	o.Credentials = &v
	return o
}

// GetName returns the Name field value
func (o *GCPProvider) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GCPProvider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *GCPProvider) SetName(v string) *GCPProvider {
	o.Name = &v
	return o
}

// GetProject returns the Project field value
func (o *GCPProvider) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *GCPProvider) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Project, true
}

// SetProject sets field value
func (o *GCPProvider) SetProject(v string) *GCPProvider {
	o.Project = &v
	return o
}

// GetRegion returns the Region field value
func (o *GCPProvider) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *GCPProvider) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region, true
}

// SetRegion sets field value
func (o *GCPProvider) SetRegion(v string) *GCPProvider {
	o.Region = &v
	return o
}

// GetType returns the Type field value
func (o *GCPProvider) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GCPProvider) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type, true
}

// SetType sets field value
func (o *GCPProvider) SetType(v string) *GCPProvider {
	o.Type = &v
	return o
}

func (o GCPProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GCPProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credentials"] = o.Credentials
	toSerialize["name"] = o.Name
	toSerialize["project"] = o.Project
	toSerialize["region"] = o.Region
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableGCPProvider struct {
	value *GCPProvider
	isSet bool
}

func (v *NullableGCPProvider) Get() *GCPProvider {
	return v.value
}

func (v *NullableGCPProvider) Set(val *GCPProvider) {
	v.value = val
	v.isSet = true
}

func (v *NullableGCPProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableGCPProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGCPProvider(val *GCPProvider) *NullableGCPProvider {
	return &NullableGCPProvider{value: val, isSet: true}
}

func (v NullableGCPProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGCPProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
